apiVersion: apps/v1
kind: Deployment
metadata:
  name: facial-emotion-model
spec:
  replicas: 2  
  selector:
    matchLabels:
      app: facial-emotion-model
  template:
    metadata:
      labels:
        app: facial-emotion-model
    spec:
      containers:
      - name: facial-emotion-model
        image: mundaneeditorial/facial-emotion-model  
        ports:
        - containerPort: 5000
