apiVersion: v1
kind: Service
metadata:
  name: facial-emotion-model-service
spec:
  selector:
    app: facial-emotion-model
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000  
  type: LoadBalancer  
